services:
  pg:
    image: postgres:15-alpine3.19
    container_name: pg
    environment:
      - "POSTGRES_DB=${PG_DBNAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PWD}"
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - shared

  chat-migrator:
    container_name: chat-migrator
    depends_on:
      - pg
    build:
      context: .
      dockerfile: migrations/Dockerfile
    restart: on-failure
    environment:
      - "PG_HOST=pg"
      - "PG_PORT=5432"
      - "PG_USER=${PG_USER}"
      - "PG_PWD=${PG_PWD}"
      - "PG_DBNAME=${PG_DBNAME}"
    networks:
      - shared
    links:
      - pg

  chat-service:
    depends_on:
      pg:
        condition: service_started
      chat-migrator:
          condition: service_completed_successfully
    build:
      context: .
    container_name: chat-service
    environment:
      - "ENV=local"
      - "GRPC_PORT=${GRPC_PORT}"
      - "PG_HOST=pg"
      - "PG_PORT=5432"
      - "PG_USER=${PG_USER}"
      - "PG_PWD=${PG_PWD}"
      - "PG_DBNAME=${PG_DBNAME}"
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    restart: always
    networks:
      - shared
    links:
      - pg

volumes:
  pg:

networks:
  shared:
    name: service-net
